#!/bin/bash 
# 
# This script runs a Turbomole job using SMP parallelization 
# 
# Grid Engine options 
#$ -N pythonRules # Name this job 




#$ -cwd # use current working directory 
#$ -o test.out # specify an output file - change 'outputfile.out' 
#$ -j y # and put all output (inc errors) into it 
#$ -pe smp 2 # Request N CPU cores 
#$ -l h_vmem=4G # Request 1GB RAM / core, i.e. 4GB total
#$ -l h_rt=10:0:0 # Request 240 hour runtime (max allowed) 
#$ -l s_rt=9:55:0 # Time at which data will copy from scratch to working directory
#$ -m ea # Send email at end of job and if aborted

export PARA_ARCH=SMP
export PARNODES=2

function Cleanup ()
{
    trap "" SIGUSR1 EXIT # Disable trap now we're in it
    # Clean up task
    cp -r  $TMPDIR/* $DATADIR/
    exit 0
}

DATADIR=/`pwd`
trap Cleanup SIGUSR1 EXIT # Enable trap

cd $TMPDIR
cp -r  $DATADIR/* $TMPDIR/

module load cp2k
module load numpy/1.10.2/python2.7

python combined.py


rm -r MPI*
rm CC*
cp -r $TMPDIR/* $DATADIR

